project:
  type: website


website:
  title: "Undergraduate Physics Lecture Notes"
  navbar:
    right:
      - icon: github
        href: https://github.com/vitenti-physics/undergrad
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-R4D0BX334F"
    anonymize-ip: true  
  sidebar:
      style: "docked"
      collapse-level: 2
      contents:
        - section: "Courses"
          contents:
            - section: "Vector Calculus"
              contents:
                - text: "Overview"
                  href: courses/vector-calculus/index.qmd
                - text: "Vector Spaces Products and Maps"
                  href: courses/vector-calculus/vector-spaces.qmd
            - section: "Mathematical Physics"
              contents:
                - text: "Overview"
                  href: courses/mathematical-physics/index.qmd
            - section: "Special Relativity"
              contents:
                - text: "Overview"
                  href: courses/special-relativity/index.qmd
                - text: "Galilean Relativity"
                  href: courses/special-relativity/galilean-relativity.qmd
                - text: "Spacetime Algebra"
                  href: courses/special-relativity/spacetime-algebra.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly      
    toc: true
    grid:
      body-width: 1200px

reference-location: margin
citation-location: margin
authors:
  - Sandro Vitenti
jupyter: python3
license: CC BY-NC-SA 4.0
